name = "singgah-temp-mail"
main = "src/worker.js"
compatibility_date = "2025-04-01"
workers_dev = true
routes = [{ pattern = "singgah-temp-mail.wanzabigail.my.id", custom_domain = true }]

[vars]
MAIL_DOMAINS = "wanzabigail.my.id"
ALLOWED_ORIGINS = "https://NAMA-PAGES.pages.dev"
EMAIL_TTL_HOURS = "24"
MAILBOX_TTL_HOURS = "168"
MAX_EMAILS_PER_ADDRESS = "50"
MAX_EMAIL_BYTES = "1048576"
POLL_INTERVAL_SECONDS = "7"
RATE_LIMIT_ENABLED = "true"
RATE_LIMIT_PER_MINUTE = "120"
CREATE_LIMIT_PER_HOUR = "20"

[[d1_databases]]
binding = "DB"
database_name = "temp-mail-db"
database_id = "33ae6d8d-678c-48e2-8f88-9693baabb40b"

[triggers]
crons = ["*/5 * * * *"]
